import Link from "next/link";

export const metadata = {
  title: "Blogs | Next Project",
  description: "Generated by create next app",
};

const blogs = [
  {
    id: 1,
    year: 2013,
    title: "title 1",
  },
  {
    id: 2,
    year: 2022,
    title: "title 2",
  },
  {
    id: 3,
    year: 2019,
    title: "title 3",
  },
  {
    id: 4,
    year: 2026,
    title: "title 4",
  },
];

const BlogsPage = () => {
  return (
    <div className="container mx-auto">
      {blogs.map(({ id, year, title }) => (
        // <li key={path} className="my-2 hover:font-bold">
        <Link
          className="block border border-green-500 p-2 my-2"
          key={id}
          // href={`/blogs/${year}/${id}`}>
          href={{
            pathname: `/blogs/${year}/${id}`,
          }}
        >
          {title}
        </Link>
        // </li>
      ))}
    </div>
  );
};

export default BlogsPage;
