/* eslint-disable @next/next/no-img-element */
export const metadata = {
  title: "About | Next Project",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="w-11/12 mx-auto my-16">
      <div className="text-center space-y-3">
        <h1 className="text-2xl font-bold">About Doctris</h1>
        <h1 className="border-2 w-14 mx-auto border-purple-700"></h1>
        <p className="w-9/12 mx-auto">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae
          risus nec dui venenatis dignissim. Aenean vitae metus in augue pretium
          ultrices. Duis dictum eget dolor vel blandit.
        </p>
      </div>

      <div className="mt-12">
          <div className="flex 
          justify-between gap-4 items-center">
            <p className="my-5">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porta
          luctus est interdum pretium. Fusce id tortor fringilla, suscipit
          turpis ac, varius ex. Cras vel ddf metus ligula. Nam enim ligula,
          bibendum a iaculis ut, cursus id augue. Proin vitae purus id tortor
          vehicula scelerisque non in libero.
        </p>
        <p className="mb-5">
          Nulla non turpis sit amet purus pharetra sollicitudin. Proin rutrum
          urna ut suscipit ullamcorper. Proin sapien felis, dignissim non
          finibus eget, luctus vel purus. Pellentesque efficitur congue orci
          ornare accumsan. Nullam ultrices libero vel imperdiet scelerisque.
          Donec vel mauris eros.
        </p>
          </div>

        <div className="my-5">
          <img
            className="w-full h-[600px] rounded-md"
            src="https://img.freepik.com/free-photo/team-doctors-smiling-conference-room_107420-84794.jpg?w=740&t=st=1709055514~exp=1709056114~hmac=9bf00391040fbf6c680d954f46bac7051b038ec6520944fe79e30fd1e653b364"
            alt=""
          />
        </div>

        <div className="flex justify-between gap-3 py-12 px-3 bg-gray-100 rounded-md">
          <div classname="space-y-4">
            <h1 className="text-xl font-bold">Our Mission</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porta
              luctus est interdum pretium. Fusce id tortor fringilla.
            </p>
          </div>
          <div classname="space-y-4">
            <h1 className="text-xl font-bold">Our Vission</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porta
              luctus est interdum pretium. Fusce id tortor fringilla.
            </p>
          </div>
          <div classname="space-y-4">
            <h1 className="text-xl font-bold">Our Plan</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porta
              luctus est interdum pretium. Fusce id tortor fringilla.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
