export const metadata = {
  title: "Add Product | Next Project",
  description: "Generated by create next app",
};


const AddProductPage = () => {
    return <div>This is AddProductPage</div>;
};

export default AddProductPage;