export const metadata = {
  title: "AppointmentPage | Next Project",
  description: "Generated by create next app",
};

const AppoinmentPage = () => {
    return (
        <div className="my-12">
           <h1 className="text-center font-bold text-2xl text-purple-600">Appointment Section content coming soon.............</h1>
        </div>
    );
};

export default AppoinmentPage;