export const metadata = {
  title: "Manage Product | Next Project",
  description: "Generated by create next app",
};

const ManageProductPage = () => {
    return <div>This is ManageProductPage</div>;
};

export default ManageProductPage;