"use client"

// export const metadata = {
//   title: "Single Blog | Next Project",
//   description: "Generated by create next app",
// };

const SingleBlog = ({ params, searchParams }) => {
  const [year, id] = params.segments || [];
  // const params2 = useParams();
  // const searchParams2 = useSearchParams();
    // console.log(segments, params);
  return <div>
    This is single blog {year || new Date().getFullYear} for {id}
    {
      searchParams.title
    }
  </div>;
};

export default SingleBlog;
